# Site settings
metatitle: "Booster Apps"
title: "Booster Apps"
header-img: img/home-bg.jpg
email: steve@shopifyboosterapps.com
description: "Creating apps to boost your shopify experience"
baseurl: ""
url: "http://shopfifyboosterapps.com"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
