# Site settings
metatitle: "Gopher Labs: GoLang Consulting Services"
title: "Gopher Labs Blog"
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
description: "Gopher Labs: GoLang Consulting Services"
baseurl: ""
url: "http://gopherlabs.io"
twitter_username: gopherlabsio

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
